initial commit

diff --git a/.github/workflows/web-deploy-ipfs.yml b/.github/workflows/web-deploy-ipfs.yml
--- a/.github/workflows/web-deploy-ipfs.yml
+++ b/.github/workflows/web-deploy-ipfs.yml
@@ -12,6 +12,10 @@ jobs:
   ## - latest_tag: the tag of the latest release
   ## - tar_url: the URL of the tarball of the latest release
   ## - checksum_url: the URL of the checksum of the latest release
+  ## Environment variables:
+  ## - TAG_NAME: the tag of the latest release
+  ## - TAR_URL: the URL of the tarball of the latest release
+  ## - CHECKSUM_URL: the URL of the checksum of the latest release
   check-release:
     runs-on: ubuntu-latest
     name: Check for new release
@@ -20,9 +24,10 @@ jobs:
       latest_tag: ${{ steps.latest_release.outputs.latest_tag }}
       tar_url: ${{ steps.latest_release.outputs.tar_url }}
       checksum_url: ${{ steps.latest_release.outputs.checksum_url }}
+
     steps:
       - name: Get latest release info
-        id: latest_release
+        id: latest_release_info
         run: |
           API_URL="https://api.github.com/repos/safe-global/safe-wallet-monorepo/releases/latest"
           RELEASE_INFO=$(curl -s $API_URL)
@@ -38,7 +43,14 @@ jobs:
           echo "tar_url=$TAR_URL" >> $GITHUB_OUTPUT
           echo "checksum_url=$CHECKSUM_URL" >> $GITHUB_OUTPUT
 
-      - name: Compare with Stored Tag (.prev_release)
+      - name: Restore last release tag
+        id: restore-cache
+        uses: actions/cache@v4
+        with:
+          path: .prev_release
+          key: latest-release
+
+      - name: Compare current tag with cached release tag
         id: compare
         run: |
           PREV_TAG_NAME=$(cat .prev_release 2>/dev/null || echo "none")
@@ -59,27 +71,29 @@ jobs:
         uses: actions/cache@v4
         with:
           path: .prev_release
-          key: latest-release-${{ env.TAG_NAME }}
+          key: latest-release
 
   ## Deploy the web app to IPFS
+  ## Outputs:
+  ## - ipfs_hash: the IPFS hash of the deployed web app
   deploy:
-    runs-on: ubuntu-latest
-    needs: check-release
     if: ${{ needs.check-release.outputs.new_release == 'true' }}
-
+    runs-on: ubuntu-latest
+    name: Deploy to IPFS
+    needs: check-release
+    outputs:
+      ipfs_hash: ${{ steps.deploy_ipfs.outputs.cid }}
     permissions:
       contents: read
       statuses: write
       checks: write
       pull-requests: write
 
-    name: Deploy to IPFS
-
     steps:
       - name: Download Tarball and Checksum
         run: |
-          curl -L "${{ needs.check-release.outputs.tar_url }}" -o /tmp/release.tar.gz
-          curl -L "${{ needs.check-release.outputs.checksum_url }}" -o /tmp/checksum.txt
+          curl -L "${{ needs.check-release.outputs.tar_url }}" -o /tmp/release.tar.gz  || { echo "Download failed!" >&2; exit 1; }
+          curl -L "${{ needs.check-release.outputs.checksum_url }}" -o /tmp/checksum.txt  || { echo "Download failed!" >&2; exit 1; }
 
       - name: Verify Checksum
         run: |
@@ -110,7 +124,7 @@ jobs:
 
       - name: Deploy to IPFS
         uses: ipfs/ipfs-deploy-action@v1
-        id: deploy
+        id: deploy_ipfs
         with:
           path-to-deploy: /tmp/release/out
           storacha-key: ${{ secrets.STORACHA_KEY }}
@@ -119,3 +133,42 @@ jobs:
           github-token: ${{ secrets.GITHUB_TOKEN }}
           # set-github-status: "false"
           # set-pr-comment: "false"
+
+      - name: Print IPFS hash and add to outputs
+        run: |
+          echo "IPFS hash: ${{ steps.deploy_ipfs.outputs.cid }}"
+          echo "ipfs_hash=${{ steps.deploy_ipfs.outputs.cid }}" >> $GITHUB_OUTPUT
+
+      - name: Clean up temporary files
+        run: |
+          rm -rf /tmp/release /tmp/checksum.txt /tmp/release.tar.gz
+
+  ## Create a release on GitHub
+  release_note:
+    if: ${{ needs.deploy.outputs.ipfs_hash != '' }}
+    runs-on: ubuntu-latest
+    name: Create Release Note
+    needs: deploy
+    permissions:
+      contents: read
+      statuses: write
+      checks: write
+      pull-requests: write
+
+    steps:
+      - name: Create Release
+        id: create_release
+        uses: actions/create-release@v1
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          tag_name: ${{ env.TAG_NAME }}
+          release_name: Release ${{ env.TAG_NAME }}
+          body: |
+            ## Safe-Wallet-Monorepo on IPFS Release
+            - Version: ${{ env.TAG_NAME }}
+            - Release link: https://github.com/safe-global/safe-wallet-monorepo/releases/tag/${{ env.TAG_NAME }}
+            - IPFS hash: ${{ needs.deploy.outputs.ipfs_hash }}
+            - IPFS link: https://${{ needs.deploy.outputs.ipfs_hash }}.ipfs.w3s.link/
+          draft: false
+          prerelease: false
